# Generated by Django 5.1 on 2024-09-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
    ]
